-- ============================================================
-- Intelligence Engine v1.0
-- Suppliers, Purchase Orders, Consumption History, Decisions
-- ============================================================

-- Suppliers master table
CREATE TABLE IF NOT EXISTS suppliers (
    id                  TEXT        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "tenantId"          TEXT        NOT NULL,
    name                TEXT        NOT NULL,
    code                TEXT,
    categories          TEXT[]      NOT NULL DEFAULT '{}',
    "contactEmail"      TEXT,
    "contactPhone"      TEXT,
    "leadTimeDays"      INTEGER     NOT NULL DEFAULT 3,
    "minOrderValue"     DECIMAL(12,2),
    "totalOrders"       INTEGER     NOT NULL DEFAULT 0,
    "onTimeDeliveries"  INTEGER     NOT NULL DEFAULT 0,
    "lateDeliveries"    INTEGER     NOT NULL DEFAULT 0,
    "isActive"          BOOLEAN     NOT NULL DEFAULT true,
    "createdAt"         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_suppliers_tenant      ON suppliers ("tenantId");
CREATE INDEX IF NOT EXISTS idx_suppliers_tenant_active ON suppliers ("tenantId", "isActive");

-- Purchase orders
CREATE TABLE IF NOT EXISTS purchase_orders (
    id                    TEXT        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "tenantId"            TEXT        NOT NULL,
    "supplierId"          TEXT        NOT NULL REFERENCES suppliers(id),
    status                TEXT        NOT NULL DEFAULT 'draft',
    "sourceDecisionId"    TEXT,
    "totalEstimatedCost"  DECIMAL(14,2),
    "totalActualCost"     DECIMAL(14,2),
    currency              TEXT        NOT NULL DEFAULT 'BRL',
    "requestedDelivery"   TIMESTAMPTZ,
    "confirmedDelivery"   TIMESTAMPTZ,
    "actualDelivery"      TIMESTAMPTZ,
    "relatedEventId"      TEXT,
    notes                 TEXT,
    "createdAt"           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_purchase_orders_tenant         ON purchase_orders ("tenantId");
CREATE INDEX IF NOT EXISTS idx_purchase_orders_tenant_status  ON purchase_orders ("tenantId", status);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_tenant_supplier ON purchase_orders ("tenantId", "supplierId");

-- Purchase order line items
CREATE TABLE IF NOT EXISTS purchase_order_items (
    id                  TEXT        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "purchaseOrderId"   TEXT        NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    "inventoryItemId"   TEXT,
    "itemCode"          TEXT        NOT NULL,
    "itemName"          TEXT        NOT NULL,
    category            TEXT,
    "quantityOrdered"   DECIMAL(12,3) NOT NULL,
    unit                TEXT        NOT NULL,
    "unitPrice"         DECIMAL(12,4),
    "totalPrice"        DECIMAL(14,2),
    "quantityReceived"  DECIMAL(12,3),
    status              TEXT        NOT NULL DEFAULT 'pending',
    "createdAt"         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_poi_order ON purchase_order_items ("purchaseOrderId");

-- Event consumption history (training data for forecast engine)
CREATE TABLE IF NOT EXISTS event_consumption_history (
    id                  TEXT        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "tenantId"          TEXT        NOT NULL,
    "eventId"           TEXT,
    "eventType"         TEXT        NOT NULL,
    "guestCount"        INTEGER     NOT NULL,
    "durationHours"     DECIMAL(4,1) NOT NULL DEFAULT 6,
    "itemCode"          TEXT        NOT NULL,
    "itemName"          TEXT        NOT NULL,
    category            TEXT        NOT NULL,
    "quantityConsumed"  DECIMAL(12,3) NOT NULL,
    unit                TEXT        NOT NULL,
    "perGuestRate"      DECIMAL(10,6) NOT NULL,
    "recordedAt"        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ech_tenant_type     ON event_consumption_history ("tenantId", "eventType");
CREATE INDEX IF NOT EXISTS idx_ech_tenant_item     ON event_consumption_history ("tenantId", "itemCode");
CREATE INDEX IF NOT EXISTS idx_ech_tenant_type_item ON event_consumption_history ("tenantId", "eventType", "itemCode");

-- Operational decisions (generated by decision engine)
CREATE TABLE IF NOT EXISTS operational_decisions (
    id               TEXT        NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "tenantId"       TEXT        NOT NULL,
    action           TEXT        NOT NULL,
    confidence       DECIMAL(4,3) NOT NULL,
    "riskLevel"      TEXT        NOT NULL,
    payload          JSONB       NOT NULL,
    status           TEXT        NOT NULL DEFAULT 'pending',
    "executedAt"     TIMESTAMPTZ,
    "executedBy"     TEXT,
    "relatedEventId" TEXT,
    "relatedOrderId" TEXT,
    "expiresAt"      TIMESTAMPTZ,
    "createdAt"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_od_tenant         ON operational_decisions ("tenantId");
CREATE INDEX IF NOT EXISTS idx_od_tenant_status  ON operational_decisions ("tenantId", status);
CREATE INDEX IF NOT EXISTS idx_od_tenant_action  ON operational_decisions ("tenantId", action);
CREATE INDEX IF NOT EXISTS idx_od_tenant_expires ON operational_decisions ("tenantId", status, "expiresAt");

-- Seed demo supplier data for the default tenant
INSERT INTO suppliers (id, "tenantId", name, code, categories, "contactEmail", "leadTimeDays", "isActive")
SELECT
    gen_random_uuid()::text,
    t.id::text,
    'Distribuidora Central Bebidas',
    'SUP-001',
    ARRAY['beverage_alcohol','beverage_soft','beverage_water'],
    'compras@centralbebs.com.br',
    2,
    true
FROM tenants t
ORDER BY t.created_at
LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO suppliers (id, "tenantId", name, code, categories, "contactEmail", "leadTimeDays", "isActive")
SELECT
    gen_random_uuid()::text,
    t.id::text,
    'Frigorífico São Paulo',
    'SUP-002',
    ARRAY['consumable','perishable'],
    'pedidos@frigosp.com.br',
    1,
    true
FROM tenants t
ORDER BY t.created_at
LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO suppliers (id, "tenantId", name, code, categories, "contactEmail", "leadTimeDays", "isActive")
SELECT
    gen_random_uuid()::text,
    t.id::text,
    'Importadora Premium Drinks',
    'SUP-003',
    ARRAY['beverage_spirit','beverage_alcohol'],
    'premium@importadora.com.br',
    5,
    true
FROM tenants t
ORDER BY t.created_at
LIMIT 1
ON CONFLICT DO NOTHING;
